### ISSUE TITLE
[BUG] 应用奔溃

### ISSUE THREAD

**Issue by lhtrus** [MetaCubeX/ClashMetaForAndroid#33]
### 描述此错误

应用闪退报错

### 如何复现该错误

步骤 1: 下载最新cmfa-2.5.13
步骤 2: 安装
步骤 3: 打开应用即奔溃报错

### 设备信息

- 机型:redmi 10X 5G
- 系统类型:AOSP
- Android 版本:12

### 应用信息

- 版本:cmfa-2.5.13
- 安装包文件名:cmfa-2.5.13-pre03-meta-alpha-arm64-v8a-release.apk
- 应用来源:github

### 配置文件

```yml
无配置
```

### 日志

```raw
12-11 13:15:30.558 29410 29410 D ClashForAndroid: Process com.github.metacubex.clash.meta:background started
12-11 13:15:32.377 29596 29596 D ClashForAndroid: Process com.github.metacubex.clash.meta started
12-11 13:15:32.407 29410 29625 I ClashForAndroid: Reschedule all profiles update
12-11 13:15:32.418 29410 29625 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
12-11 13:15:32.418 29410 29625 E AndroidRuntime: Process: com.github.metacubex.clash.meta:background, PID: 29410
12-11 13:15:32.418 29410 29625 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(Unknown Source:4)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at com.github.kr328.clash.service.data.ImportedDao_Impl$8.call(ImportedDao_Impl.java:4)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:2)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-11 13:15:32.418 29410 29625 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2f42342, Dispatchers.IO]
12-11 13:15:32.497 29596 29596 W ClashForAndroid: RemoteManager crashed
12-11 13:15:33.526 29652 29652 D ClashForAndroid: Process com.github.metacubex.clash.meta:background started
12-11 13:15:33.532 29652 29679 I ClashForAndroid: Reschedule all profiles update
12-11 13:15:33.541 29652 29679 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
12-11 13:15:33.541 29652 29679 E AndroidRuntime: Process: com.github.metacubex.clash.meta:background, PID: 29652
12-11 13:15:33.541 29652 29679 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(Unknown Source:4)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at com.github.kr328.clash.service.data.ImportedDao_Impl$8.call(ImportedDao_Impl.java:4)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:2)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-11 13:15:33.541 29652 29679 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9d9258d, Dispatchers.IO]
12-11 13:15:33.549 29652 29673 D ClashForAndroid: Home = /data/user/0/com.github.metacubex.clash.meta/files/clash
12-11 13:15:33.587 29652 29690 I ClashForAndroid: Start initial configuration in progress
12-11 13:15:33.587 29652 29690 I ClashForAndroid: Geodata Loader mode: memconservative
12-11 13:15:33.595 29652 29688 I ClashForAndroid: Initial configuration complete, total time: 8ms
12-11 13:15:33.595 29652 29688 I ClashForAndroid: Sniffer is closed
12-11 13:15:33.596 29652 29688 I ClashForAndroid: Start initial compatible provider default
12-11 13:15:33.597 29652 29738 I ClashForAndroid: Use IPv6
12-11 13:15:33.618 29596 29596 E AndroidRuntime: FATAL EXCEPTION: main
12-11 13:15:33.618 29596 29596 E AndroidRuntime: Process: com.github.metacubex.clash.meta, PID: 29596
12-11 13:15:33.618 29596 29596 E AndroidRuntime: java.lang.IllegalArgumentException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2410)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2393)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2335)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at com.github.kr328.clash.service.remote.IProfileManagerProxy.queryActive(IProfileManager.kt:10)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at com.github.kr328.clash.service.remote.IProfileManagerProxy$queryActive$1.invokeSuspend(Unknown Source:11)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
12-11 13:15:33.618 29596 29596 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a49e90d, Dispatchers.Main]
12-11 13:15:41.012 29790 29790 D ClashForAndroid: Process com.github.metacubex.clash.meta started
12-11 13:15:41.084 29817 29817 D ClashForAndroid: Process com.github.metacubex.clash.meta:background started
12-11 13:15:41.091 29817 29847 I ClashForAndroid: Reschedule all profiles update
12-11 13:15:41.099 29817 29847 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
12-11 13:15:41.099 29817 29847 E AndroidRuntime: Process: com.github.metacubex.clash.meta:background, PID: 29817
12-11 13:15:41.099 29817 29847 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(Unknown Source:4)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at com.github.kr328.clash.service.data.ImportedDao_Impl$8.call(ImportedDao_Impl.java:4)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:2)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-11 13:15:41.099 29817 29847 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9d9258d, Dispatchers.IO]
12-11 13:15:41.118 29790 29790 E AndroidRuntime: FATAL EXCEPTION: main
12-11 13:15:41.118 29790 29790 E AndroidRuntime: Process: com.github.metacubex.clash.meta, PID: 29790
12-11 13:15:41.118 29790 29790 E AndroidRuntime: android.os.DeadObjectException
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:571)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.github.kr328.clash.service.remote.IRemoteServiceProxy.clash(IRemoteService.kt:6)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.github.kr328.clash.util.RemoteKt.withClash(Remote.kt:9)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.github.kr328.clash.util.RemoteKt.withClash$default(Remote.kt:2)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.github.kr328.clash.MainActivity.fetch(MainActivity.kt:8)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.github.kr328.clash.MainActivity.main(MainActivity.kt:6)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.github.kr328.clash.MainActivity$main$1.invokeSuspend(Unknown Source:11)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-11 13:15:41.118 29790 29790 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3700d61, Dispatchers.Main]
12-11 13:15:42.235 29864 29864 D ClashForAndroid: Process com.github.metacubex.clash.meta:background started
12-11 13:15:42.248 29864 29882 I ClashForAndroid: Reschedule all profiles update
12-11 13:15:42.263 29864 29882 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
12-11 13:15:42.263 29864 29882 E AndroidRuntime: Process: com.github.metacubex.clash.meta:background, PID: 29864
12-11 13:15:42.263 29864 29882 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(Unknown Source:4)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at com.github.kr328.clash.service.data.ImportedDao_Impl$8.call(ImportedDao_Impl.java:4)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:2)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-11 13:15:42.263 29864 29882 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9d9258d, Dispatchers.IO]
12-11 13:15:43.206 29886 29886 D ClashForAndroid: Process com.github.metacubex.clash.meta started
12-11 13:15:43.288 29912 29912 D ClashForAndroid: Process com.github.metacubex.clash.meta:background started
12-11 13:15:43.296 29912 29945 I ClashForAndroid: Reschedule all profiles update
12-11 13:15:43.305 29912 29927 D ClashForAndroid: Home = /data/user/0/com.github.metacubex.clash.meta/files/clash
12-11 13:15:43.306 29912 29945 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
12-11 13:15:43.306 29912 29945 E AndroidRuntime: Process: com.github.metacubex.clash.meta:background, PID: 29912
12-11 13:15:43.306 29912 29945 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(Unknown Source:4)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at com.github.kr328.clash.service.data.ImportedDao_Impl$8.call(ImportedDao_Impl.java:4)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:2)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-11 13:15:43.306 29912 29945 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2f42342, Dispatchers.IO]
12-11 13:15:43.360 29886 29886 W ClashForAndroid: RemoteManager crashed
12-11 13:15:43.361 29886 29886 W ClashForAndroid: Remote services panic
12-11 13:15:44.464 29959 29959 D ClashForAndroid: Process com.github.metacubex.clash.meta:background started
12-11 13:15:44.473 29959 29977 I ClashForAndroid: Reschedule all profiles update
12-11 13:15:44.481 29959 29974 D ClashForAndroid: Home = /data/user/0/com.github.metacubex.clash.meta/files/clash
12-11 13:15:44.490 29959 29977 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
12-11 13:15:44.490 29959 29977 E AndroidRuntime: Process: com.github.metacubex.clash.meta:background, PID: 29959
12-11 13:15:44.490 29959 29977 E AndroidRuntime: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(Unknown Source:4)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.room.RoomDatabase.inTransaction(Unknown Source:2)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at com.github.kr328.clash.service.data.ImportedDao_Impl$8.call(ImportedDao_Impl.java:4)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at androidx.room.CoroutinesRoom$Companion$execute$4$job$1.invokeSuspend(CoroutinesRoom.kt:2)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:20)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-11 13:15:44.490 29959 29977 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2f42342, Dispatchers.IO]
12-11 13:15:44.542 29886 29886 W ClashForAndroid: RemoteManager crashed
12-11 13:15:44.542 29886 29886 W ClashForAndroid: Remote services panic
12-11 13:15:44.578 29886 29886 I ClashForAndroid: App version: versionName = 2.5.13-pre03.Meta-Alpha versionCode = 205013
```

**Comment by 2ndMessiah** [comment]
没错，现在是近乎不能用的状态。主要用hysteria。开启之后，自动测速一下，核心就崩溃了。

**Comment by xz-dev** [comment]
删除 /data/data/com.github.metacubex.clash.meta/databases 后重新添加订阅即可

**Comment by xz-dev** [comment]
> @xz-dev 能访问这里了为啥不直接用cfm?

不是每个人都喜欢在手机上打命令

**Comment by lhtrus** [comment]
> 因为数据库版本没更新，删除 /data/data/com.github.metacubex.clash.meta/databases 后重新添加订阅即可

已成功感谢分享

**Comment by xz-dev** [comment]
> > 因为数据库版本没更新，删除 /data/data/com.github.metacubex.clash.meta/databases 后重新添加订阅即可
> 
> 已成功感谢分享

代码问题，等他修好再 close，现在先别

**Comment by 2ndMessiah** [comment]
今晚上清除了一下应用数据 歪打正着了 谢谢回复

xz-dev ***@***.***> 于 2022年12月12日周一 15:46写道：

**Comment by ipcjs** [comment]
[F-Droid](https://f-droid.org/zh_Hans/packages/com.github.metacubex.clash.meta/)上还是有问题的版本😵

**Comment by txyyh** [comment]
@ipcjs F-Droid 构建不受被构建项目本身控制

**Comment by stevejohnson7** [comment]
请前往 https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/Prerelease-alpha 尝试一下最新pre-release版，内核已升级到最新。自用hysteria2没有发现崩溃问题
